### ISSUE TITLE
Deliverable 1

### ISSUE THREAD

**Issue by xsalinassoto** [LUC-Intro-to-Web-Development/lab-1-version-control-practice-with-git-and-github-xsalinassoto#1]
![lab1 issues](https://github.com/LUC-Intro-to-Web-Development/lab-1-version-control-practice-with-git-and-github-xsalinassoto/assets/112523359/b40076d3-1861-47b1-8eff-801440f39f4d)

Prof. Fulton - I ended up using git clone. I ran into issues with git remote. I kept getting a message that said "error: failed to push some refs to [url]". After many tries, I decided to try something else.

**Comment by xsalinassoto** [comment]
This is a better screenshot.
![image](https://github.com/LUC-Intro-to-Web-Development/lab-1-version-control-practice-with-git-and-github-xsalinassoto/assets/112523359/2a3d60d8-6508-466b-b0bb-cb9700f3735b)

**Comment by instructorc** [comment]
Thanks, Xitlali - Cloning is one way to bring the project down, but you can also run the commands below to pull files directly to your computer.  The terminal image should also display the commits I've made to create the log.

git remote add [ALIAS_TYPICALLY_ORIGIN] [URL_TO_REPOSITORY]
git branch -M main
git pull [ALIAS_TYPICALLY_ORIGIN] main
