### ISSUE TITLE
Deliverable 2

### ISSUE THREAD

**Issue by xsalinassoto** [LUC-Intro-to-Web-Development/lab-1-version-control-practice-with-git-and-github-xsalinassoto#2]
![lab1 issues commit1](https://github.com/LUC-Intro-to-Web-Development/lab-1-version-control-practice-with-git-and-github-xsalinassoto/assets/112523359/7b0bbe32-b6ff-43d1-9237-11f7fe63c87d)

![lab1 issues commit2](https://github.com/LUC-Intro-to-Web-Development/lab-1-version-control-practice-with-git-and-github-xsalinassoto/assets/112523359/ad055909-cb39-4648-86bc-6e76272ab503)

**Comment by instructorc** [comment]
If you enter ":wq", that will close the comment section in the terminal.  Deliverable met!
